### PR TITLE
Router

### PR DESCRIPTION
**Pull request by adbh94**
Implemented dynamic routing using Bellman-Ford. Routers perform dynamic routing every 5s for 1s per iteration. Routers broadcast distance estimates every time new information is received.

### CODE REVIEW

**Comment by kexinrong** [comment]
Have you tried running it? How are the results?

**Comment by adbh94** [comment]
I haven't run it because I suspect other code like env.py will need to be updated. For example, there is no add_link() (replaced by add_links()) or static_routing() methods in router.py anymore.

**Comment by kexinrong** [comment]
There's only so much one can catch by reading the code. Especially in a complicated system like ours, I would like to see whether this logic can properly interact with other components. I would at least make it runnable.

**Comment by adbh94** [comment]
@sdhpzhtk  Why don't we meet sometime tomorrow or Wednesday to get this in production? You seem to have figured out how make your dynamic routing runnable. Perhaps you can take over this implementation of dynamic routing by making the other files you've built compatible with this router implementation?

**Comment by adbh94** [comment]
I just updated the implementation to perform continuous dynamic routing. Now, dynamic routing is instigated every 5s when the routers broadcast their distance estimates. However, routers respond to RoutingUpdatePackets at any time in the simulation and update their routing tables immediately after receiving new information. This potentially allows packets to start being forwarded without waiting for an entire dynamic routing session at the start of the simulation.

**Comment by sdhpzhtk** [comment]
@adbh94 I still DO NOT UNDERSTAND why you are repeating the work I DID. Please respect the work I have done. We should definitely meet tonight if possible or early tomorrow before the team meeting. Please respond at your earliest convenience. I am adding complete documentation in my next push.

**Comment by adbh94** [comment]
@sdhpzhtk I responded to your Doodle poll for a meeting. I did not repeat the work you did. In fact, in many ways I built on top of the work you did. I copied and pasted a lot of your code.

This implementation looks different for two reasons. I cleaned up the code and added documentation. Also, I changed our fundamental router design to do continuous dynamic routing. We can clear all this up in person.

**Comment by sdhpzhtk** [comment]
@adbh94 When are you back at Caltech? You and I should meet before the team meeting to finish dynamic routing.

**Comment by adbh94** [comment]
I am back at 10pm tonight. Let's meet sometime tomorrow evening, perhaps 9pm before our team meeting at 10pm.

**Comment by sdhpzhtk** [comment]
@adbh94 In that case, can we meet tonight? You are getting into same errors as my first version.  Each router should store all the distance to other nodes using a specific link, instead of only keep track of the min distance to a node. If you only keep track of the min distance to a node, then if a optimal link becomes stuck, then your router will still go to that link.

In fact, the only difference here is you are doing broadcasting whenever the routing table change, and this is some very simple change in my code. Therefore, stop working on this branch.

**Comment by adbh94** [comment]
@sdhpzhtk I cannot meet tonight because of other commitments. It'll be fine if we meet tomorrow between 7-10pm before the team meeting.

**Comment by sdhpzhtk** [comment]
@adbh94 Let's meet 7pm then. Do you understand why your routing is not working and it is a repetition of what I have done?

**Comment by adbh94** [comment]
@sdhpzhtk Ok I'll see you at 7pm. I'm not sure why mine is a repetition of your code actually. I didn't fully understand your code, so I built off whatever I did comprehend. I also feel like it should be fine keeping track of only the min distance to every node, as Bellman-Ford prescribes. If the optimal link becomes congested, this will be corrected by future dynamic routing iterations. It might be easier for you to explain in person tomorrow.

**Comment by sdhpzhtk** [comment]
@adbh94 It is a repetition of my past code, as the current way you are doing is not correct, and that is why I changed the design to my current code. So it is a repetition of the work/debugging I have done. Anyways, STOP working on this branch, and I will add documentation on my branch and explain it to you tomorrow night.

**Comment by sdhpzhtk** [comment]
@adbh94  By the way, Bellman ford will only work if a router knows the distance between ALL the nodes. Not just the min distance between the router itsdelf and other nodes. That is why all routers should store the dist between all the nodes, instead of the min dist. 

If you still cannot see why your implementation fails, here is one example:

you have a router R that have two links L1 and L2 that will eventually link to HOST1. Assume L1 and L2 are same as fast if it is empty. Now L1 is your optimal link, and you store your min dist to HOST1 as 1.0. Now if L1 become congested, you will receive a packet from L1 that tells you the dist to HOST1 is 2.0 now. Then your algorithm WILL NOT DO ANYTHING to change the routing table, while it should go to L2 instead.

**Comment by sdhpzhtk** [comment]
@adbh94 Also we decided to use 
link.buffer_size / link_rate + link_delay
as our link weight, because env.now will give you a rounded integer, instead of a more accurate float estimate. And it is causing trouble in dynamic routing. If you even bother to see my past code history, instead of my current implementation, you can see that I did use env.now - timestamp, but it does not give an accurate estimate of the link propagation.

**Comment by sdhpzhtk** [comment]
@adbh94 Therefore, please stop starting everything from scratch, because you will end up the same path as mine, and I have already done those. Stop working on this branch.

**Comment by adbh94** [comment]
@sdhpzhtk I'm done working on this branch. Your points above are valid. I'm not convinced that this is a complete repetition of your code, but we'll discuss that in person tomorrow.

If there's something to take away from this, it is PLEASE DOCUMENT YOUR CODE! Remember, it is the burden of the programmer to make the code clear and understandable, especially after filing a merge request. I cannot be the one examining your code history and reading your mind.

**Pull request closed without merging**
